### ISSUE TITLE
form.$invalid = true after loading correct data without focusing international-phone-number element

### ISSUE THREAD

**Issue by sergeymurashko** [mareczek/international-phone-number#58] opened 2015-07-17 08:28 UTC
Hi Mareczek,

I have a form where I'm trying to edit phone number with international-phone-number element. After loading form I'm able to see data in input element (it contains valid phone number), but form has form.$invalid = true.
Focus this element makes form.$invalid = false. 

Could you please look at this case? Thanks in advance.

**Comment by mareczek** [comment] 2015-07-17 09:00
Hi, I have the same problem. Will be fixing this really soon :-)

**Comment by 7867praveen** [comment] 2015-07-18 09:48
@sergeymurashko I have the same problem but I used a temporary solution. Use $pristine with $invalid so on load only validate if filed is edited.

**Comment by mareczek** [comment] 2015-09-03 08:22
Should be fixed in 0.0.11

**Comment by antoinepairet** [comment] 2015-09-07 15:50
@mareczek I just updated to 0.0.11. The issue is still present.
regards

**Comment by antoinepairet** [comment] 2015-09-07 18:49
@mareczek I can confirm the issue is fixed. Thanks!

**Closed** 2015-09-08 05:56 UTC
